Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/09/2023
Var
   // Seção de Declarações das variáveis
   numero : inteiro
   
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Digite um número: ")
   Leia (numero)
   limpatela

   Se (numero % 2 = 0) entao
      escreval ("Par.")
   Senao
      escreval ("Impar.")
   fimse
Fimalgoritmo